"""Add image_url to Location

Revision ID: 56901ef73b5c
Revises: 875d20a43819
Create Date: 2025-06-13 21:36:10.727473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56901ef73b5c'
down_revision = '875d20a43819'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
