"""add game_type, data, relationships

Revision ID: 670539392f6c
Revises: 56901ef73b5c
Create Date: 2025-07-09 16:37:09.441235

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '670539392f6c'
down_revision = '56901ef73b5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('data', sqlite.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('data')
        batch_op.drop_column('game_type')

    # ### end Alembic commands ###
