"""Add discoverability to Game

Revision ID: 98ccfb9303f0
Revises: 00a1c888dcfb
Create Date: 2025-07-15 15:37:23.935793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98ccfb9303f0'
down_revision = '00a1c888dcfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discoverability', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('discoverability')

    # ### end Alembic commands ###
