"""change to Game discoverable

Revision ID: f7014566db00
Revises: 98ccfb9303f0
Create Date: 2025-07-15 15:48:55.079905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7014566db00'
down_revision = '98ccfb9303f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discoverable', sa.String(length=20), nullable=True))
        batch_op.drop_column('discoverability')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discoverability', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('discoverable')

    # ### end Alembic commands ###
