"""Add GameType table and gametype_id to Game

Revision ID: 00a1c888dcfb
Revises: 670539392f6c
Create Date: 2025-07-09 16:39:49.828655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00a1c888dcfb'
down_revision = '670539392f6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gametype_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_game_gametype_id', 'game_type', ['gametype_id'], ['id'])
        batch_op.drop_column('game_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_type', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('gametype_id')

    # ### end Alembic commands ###
