"""add bbox to game

Revision ID: 2cf703c1fae8
Revises: 7b4f97d173e6
Create Date: 2025-07-25 20:37:30.046513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cf703c1fae8'
down_revision = '7b4f97d173e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('max_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('min_lon', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('max_lon', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('max_lon')
        batch_op.drop_column('min_lon')
        batch_op.drop_column('max_lat')
        batch_op.drop_column('min_lat')

    # ### end Alembic commands ###
