"""Add data column to Team

Revision ID: 68048eaa09eb
Revises: eb933f684b5a
Create Date: 2025-09-13 16:01:27.257084

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '68048eaa09eb'
down_revision = 'eb933f684b5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #with op.batch_alter_table('team', schema=None) as batch_op:
    #    batch_op.add_column(sa.Column('data', sqlite.JSON(), nullable=True))

    with op.batch_alter_table('team_location_assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_index', sa.Integer(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_location_assignment', schema=None) as batch_op:
        batch_op.drop_column('order_index')

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_column('data')

    # ### end Alembic commands ###
