"""Add nullable show_pin boolean to Location

Revision ID: 7b4f97d173e6
Revises: f7014566db00
Create Date: 2025-07-16 20:25:12.229647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b4f97d173e6'
down_revision = 'f7014566db00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_pin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_column('show_pin')

    # ### end Alembic commands ###
