"""add mode and join_deadline

Revision ID: 875d20a43819
Revises: 8dd88ee87faa
Create Date: 2025-06-13 20:13:08.052333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '875d20a43819'
down_revision = '8dd88ee87faa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mode', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('join_deadline', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('join_deadline')
        batch_op.drop_column('mode')

    # ### end Alembic commands ###
