"""init setup with data and order_index

Revision ID: eb933f684b5a
Revises: 
Create Date: 2025-09-13 15:52:09.521354

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'eb933f684b5a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sqlite.JSON(), nullable=True))

    with op.batch_alter_table('team_location_assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_index', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_location_assignment', schema=None) as batch_op:
        batch_op.drop_column('order_index')

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_column('data')

    # ### end Alembic commands ###
